version: "3.9"

services:
  seto-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached
      - $HOME/.docker:/home/node/.docker
    environment:
      - seto_SRC_PATH=${PWD}
      - DOCKER_HOST=unix:///var/run/docker-host.sock
    command: sleep infinity

networks:
  default:
    attachable: true