version: "3.9"

services:
  seto-api:
    build:
      dockerfile: Dockerfile
      target: development
    ports:
      - "41100:41100"
    depends_on:
      - mongodb
    volumes:
      - .:/app

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: